#!/bin/bash

if systemctl status  firewalld.service |grep "Active: active" > /dev/null 2>&1

        then
                echo "OK: Iptables Active"
                exit 0
        else

                echo "CRITICAL: Iptables Not Active"
               
fi
